namespace SistemaGestionNomina.UI
{
    partial class FrmSolicitudesAusencia
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label lblTitulo, lblResultado;
        private System.Windows.Forms.TextBox txtBuscar;
        private System.Windows.Forms.ComboBox cmbTipo, cmbEstado, cmbDepartamento;
        private System.Windows.Forms.DateTimePicker dtpDesde, dtpHasta;
        private System.Windows.Forms.Button btnBuscar, btnNuevo, btnVer, btnGestionar, btnCancelar, btnExcel, btnPdf;
        private System.Windows.Forms.DataGridView dgvSolicitudes;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            this.lblTitulo = new System.Windows.Forms.Label(); this.lblResultado = new System.Windows.Forms.Label(); this.txtBuscar = new System.Windows.Forms.TextBox(); this.cmbTipo = new System.Windows.Forms.ComboBox(); this.cmbEstado = new System.Windows.Forms.ComboBox(); this.cmbDepartamento = new System.Windows.Forms.ComboBox(); this.dtpDesde = new System.Windows.Forms.DateTimePicker(); this.dtpHasta = new System.Windows.Forms.DateTimePicker(); this.btnBuscar = new System.Windows.Forms.Button(); this.btnNuevo = new System.Windows.Forms.Button(); this.btnVer = new System.Windows.Forms.Button(); this.btnGestionar = new System.Windows.Forms.Button(); this.btnCancelar = new System.Windows.Forms.Button(); this.btnExcel = new System.Windows.Forms.Button(); this.btnPdf = new System.Windows.Forms.Button(); this.dgvSolicitudes = new System.Windows.Forms.DataGridView(); ((System.ComponentModel.ISupportInitialize)(this.dgvSolicitudes)).BeginInit(); this.SuspendLayout();
            this.BackColor = System.Drawing.Color.FromArgb(12, 12, 18); this.ClientSize = new System.Drawing.Size(1120, 720); this.Font = new System.Drawing.Font("Segoe UI", 9F); this.ForeColor = System.Drawing.Color.FromArgb(229, 228, 245); this.Name = "FrmSolicitudesAusencia"; this.Text = "Solicitudes de ausencia"; this.Load += new System.EventHandler(this.FrmSolicitudesAusencia_Load);
            this.lblTitulo.AutoSize = true; this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold); this.lblTitulo.Location = new System.Drawing.Point(28, 20); this.lblTitulo.Text = "Solicitudes de ausencia";
            this.txtBuscar.Location = new System.Drawing.Point(34, 82); this.txtBuscar.Size = new System.Drawing.Size(160, 23);
            this.cmbDepartamento.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList; this.cmbDepartamento.Location = new System.Drawing.Point(204, 82); this.cmbDepartamento.Size = new System.Drawing.Size(170, 23);
            this.cmbTipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList; this.cmbTipo.Location = new System.Drawing.Point(384, 82); this.cmbTipo.Size = new System.Drawing.Size(155, 23);
            this.cmbEstado.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList; this.cmbEstado.Location = new System.Drawing.Point(549, 82); this.cmbEstado.Size = new System.Drawing.Size(112, 23);
            this.dtpDesde.Format = System.Windows.Forms.DateTimePickerFormat.Short; this.dtpDesde.Location = new System.Drawing.Point(671, 82); this.dtpDesde.ShowCheckBox = true; this.dtpDesde.Checked = false; this.dtpDesde.Size = new System.Drawing.Size(126, 23);
            this.dtpHasta.Format = System.Windows.Forms.DateTimePickerFormat.Short; this.dtpHasta.Location = new System.Drawing.Point(807, 82); this.dtpHasta.ShowCheckBox = true; this.dtpHasta.Checked = false; this.dtpHasta.Size = new System.Drawing.Size(126, 23);
            this.btnBuscar.BackColor = System.Drawing.Color.FromArgb(124, 58, 237); this.btnBuscar.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnBuscar.Location = new System.Drawing.Point(943, 78); this.btnBuscar.Size = new System.Drawing.Size(80, 31); this.btnBuscar.Text = "Buscar"; this.btnBuscar.UseVisualStyleBackColor = false; this.btnBuscar.Click += new System.EventHandler(this.btnBuscar_Click);
            this.btnNuevo.BackColor = System.Drawing.Color.FromArgb(124, 58, 237); this.btnNuevo.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnNuevo.Location = new System.Drawing.Point(34, 126); this.btnNuevo.Size = new System.Drawing.Size(100, 32); this.btnNuevo.Text = "Nueva"; this.btnNuevo.UseVisualStyleBackColor = false; this.btnNuevo.Click += new System.EventHandler(this.btnNuevo_Click);
            this.btnVer.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnVer.Location = new System.Drawing.Point(142, 126); this.btnVer.Size = new System.Drawing.Size(100, 32); this.btnVer.Text = "Ver detalle"; this.btnVer.Click += new System.EventHandler(this.btnVer_Click);
            this.btnGestionar.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnGestionar.Location = new System.Drawing.Point(250, 126); this.btnGestionar.Size = new System.Drawing.Size(100, 32); this.btnGestionar.Text = "Gestionar"; this.btnGestionar.Click += new System.EventHandler(this.btnGestionar_Click);
            this.btnCancelar.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnCancelar.Location = new System.Drawing.Point(358, 126); this.btnCancelar.Size = new System.Drawing.Size(100, 32); this.btnCancelar.Text = "Cancelar"; this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            this.btnExcel.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnExcel.Location = new System.Drawing.Point(884, 126); this.btnExcel.Size = new System.Drawing.Size(66, 32); this.btnExcel.Text = "Excel"; this.btnExcel.Click += new System.EventHandler(this.btnExcel_Click);
            this.btnPdf.FlatStyle = System.Windows.Forms.FlatStyle.Flat; this.btnPdf.Location = new System.Drawing.Point(958, 126); this.btnPdf.Size = new System.Drawing.Size(66, 32); this.btnPdf.Text = "PDF"; this.btnPdf.Click += new System.EventHandler(this.btnPdf_Click);
            this.dgvSolicitudes.AllowUserToAddRows = false; this.dgvSolicitudes.AllowUserToDeleteRows = false; this.dgvSolicitudes.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; this.dgvSolicitudes.BackgroundColor = System.Drawing.Color.FromArgb(18, 18, 27); this.dgvSolicitudes.Location = new System.Drawing.Point(34, 176); this.dgvSolicitudes.MultiSelect = false; this.dgvSolicitudes.ReadOnly = true; this.dgvSolicitudes.RowHeadersVisible = false; this.dgvSolicitudes.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect; this.dgvSolicitudes.Size = new System.Drawing.Size(990, 478);
            this.dgvSolicitudes.Columns.Add("IdSolicitud", "Id"); this.dgvSolicitudes.Columns["IdSolicitud"].Visible = false; this.dgvSolicitudes.Columns.Add("Codigo", "Código"); this.dgvSolicitudes.Columns.Add("Empleado", "Empleado"); this.dgvSolicitudes.Columns.Add("Departamento", "Departamento"); this.dgvSolicitudes.Columns.Add("Tipo", "Tipo"); this.dgvSolicitudes.Columns.Add("Desde", "Desde"); this.dgvSolicitudes.Columns.Add("Hasta", "Hasta"); this.dgvSolicitudes.Columns.Add("Estado", "Estado"); this.dgvSolicitudes.Columns.Add("Solicitante", "Solicitante"); this.dgvSolicitudes.Columns.Add("Creacion", "Creada");
            this.lblResultado.AutoSize = true; this.lblResultado.Location = new System.Drawing.Point(34, 674); this.lblResultado.Text = "0 solicitudes";
            this.Controls.Add(this.lblTitulo); this.Controls.Add(this.txtBuscar); this.Controls.Add(this.cmbDepartamento); this.Controls.Add(this.cmbTipo); this.Controls.Add(this.cmbEstado); this.Controls.Add(this.dtpDesde); this.Controls.Add(this.dtpHasta); this.Controls.Add(this.btnBuscar); this.Controls.Add(this.btnNuevo); this.Controls.Add(this.btnVer); this.Controls.Add(this.btnGestionar); this.Controls.Add(this.btnCancelar); this.Controls.Add(this.btnExcel); this.Controls.Add(this.btnPdf); this.Controls.Add(this.dgvSolicitudes); this.Controls.Add(this.lblResultado); ((System.ComponentModel.ISupportInitialize)(this.dgvSolicitudes)).EndInit(); this.ResumeLayout(false); this.PerformLayout();
        }
    }
}
